"""Add advanced features tables and update task model

Revision ID: 0380d43a3b23
Revises: 618bfd191e1c
Create Date: 2026-01-29 18:27:05.649946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0380d43a3b23'
down_revision: Union[str, Sequence[str], None] = '618bfd191e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Check if tables exist before creating them
    connection = op.get_bind()

    # Create tag table if it doesn't exist
    if not connection.dialect.has_table(connection, 'tag'):
        op.create_table('tag',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('color', sa.String(length=7), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_tag_user_id'), 'tag', ['user_id'], unique=False)

    # Create task_tag junction table if it doesn't exist
    if not connection.dialect.has_table(connection, 'task_tag'):
        op.create_table('task_tag',
        sa.Column('task_id', sa.Uuid(), nullable=False),
        sa.Column('tag_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
        sa.PrimaryKeyConstraint('task_id', 'tag_id')
        )

    # Create event table if it doesn't exist
    if not connection.dialect.has_table(connection, 'event'):
        op.create_table('event',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('task_id', sa.Uuid(), nullable=True),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('event_data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('processed', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_event_processed'), 'event', ['processed'], unique=False)
        op.create_index(op.f('ix_event_task_id'), 'event', ['task_id'], unique=False)
        op.create_index(op.f('ix_event_user_id'), 'event', ['user_id'], unique=False)

    # Create notification table if it doesn't exist
    if not connection.dialect.has_table(connection, 'notification'):
        op.create_table('notification',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('task_id', sa.Uuid(), nullable=True),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('sent_time', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=20), server_default='scheduled', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    # For columns, since they may already exist on the remote database, we'll add them one by one with error handling
    # First, try to alter the status column if it hasn't been altered yet
    try:
        op.alter_column('task', 'status',
                   existing_type=sa.VARCHAR(),
                   server_default='pending',
                   nullable=False)
    except:
        # Column might already be altered
        pass

    # Add new columns one by one, ignoring errors if they already exist
    try:
        op.add_column('task', sa.Column('priority', sa.String(), server_default='medium', nullable=False))
    except:
        pass  # Column might already exist

    try:
        op.add_column('task', sa.Column('recurrence_pattern', sa.JSON(), nullable=True))
    except:
        pass  # Column might already exist

    try:
        op.add_column('task', sa.Column('reminder_time', sa.DateTime(timezone=True), nullable=True))
    except:
        pass  # Column might already exist

    try:
        op.add_column('task', sa.Column('parent_task_id', sa.Uuid(), nullable=True))
    except:
        pass  # Column might already exist

    # Add foreign key constraint for parent_task_id if it doesn't exist
    try:
        op.create_foreign_key(None, 'task', 'task', ['parent_task_id'], ['id'])
    except:
        pass  # Constraint might already exist

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop notification table
    op.drop_table('notification')

    # Drop event table
    op.drop_table('event')

    # Drop task_tag junction table
    op.drop_table('task_tag')

    # Drop tag table
    op.drop_table('tag')

    # Drop foreign key constraint for parent_task_id
    op.drop_constraint(None, 'task', type_='foreignkey')

    # Remove new columns from task table
    op.drop_column('task', 'parent_task_id')
    op.drop_column('task', 'reminder_time')
    op.drop_column('task', 'recurrence_pattern')
    op.drop_column('task', 'priority')

    # Reset the status column to its original state
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               server_default=None)
    # ### end Alembic commands ###
