"""Add conversation and message models for AI chatbot

Revision ID: 618bfd191e1c
Revises: 545db664d150
Create Date: 2025-12-21 20:55:32.257992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add missing import


# revision identifiers, used by Alembic.
revision: str = '618bfd191e1c'
down_revision: Union[str, Sequence[str], None] = '545db664d150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Add columns as nullable first to handle existing rows
    op.add_column('task', sa.Column('ai_generated', sa.Boolean(), nullable=True))
    op.add_column('task', sa.Column('ai_intent', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('task', sa.Column('ai_context_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Update existing rows to set default values
    op.execute("UPDATE task SET ai_generated = FALSE WHERE ai_generated IS NULL")

    # Now make the column non-nullable
    op.alter_column('task', 'ai_generated', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'ai_context_id')
    op.drop_column('task', 'ai_intent')
    op.drop_column('task', 'ai_generated')
    op.drop_table('message')
    op.drop_table('conversation')
    # ### end Alembic commands ###
