apiVersion: v1
kind: Service
metadata:
  name: {{ include "todogenie.frontend.fullname" . }}
  labels:
    {{- include "todogenie.labels" . | nindent 4 }}
    app: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todogenie.selectorLabels" . | nindent 4 }}
    app: frontend